name: Build Docker images from project

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build -t dimilan/testimage:latest ./backend
          docker build -t dimilan/testimage:latest ./frontend
      - name: Push images to Dockerhub
        run: |
          docker login -u ThijsGeeraert2 -p ${{ secrets.DOCKERHUBTOKEN }}
          docker push dimilan/feimage:latest
          docker push dimilan/beimage:latest
