name: Build Docker images from project

on: #[workflow_dispatch]
  push:
    branches:
      - master
    paths: 
      - 'backend'
      - 'frontend'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build -t dimilan/testimage:latest ./backend
          docker build -t dimilan/testimage:latest ./frontend
        run: |
      - name: Push images to Dockerhub
          docker login -u thijsgeeraert -p ${{ secrets.DOCKERHUBTOKEN }}
          docker push dimilan/feimage:latest
          docker push dimilan/beimage:latest
