name: manually Build Docker images from project

on: [workflow_dispatch]

push: 
  branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
 
      - name: Push images to Dockerhub
          docker login -u thijsgeeraert -p ${{ secrets.DOCKERHUBTOKEN }}
          docker push dimilan/feimage:latest
          docker push dimilan/beimage:latest

